### ISSUE TITLE
reviews_count field is missing from the API response of the reviews call 

### ISSUE THREAD

**Issue by UtsavPreet** [jayeshsolanki93/zomato.js#1]
z
.reviews({
                res_id:18306530
            })
            .then(function (data) {
                console.log(data);})
The data misses the: "reviews_count" attribute which is present in the JSON returned by official API.

**Comment by jayeshsolanki93** [comment]
Yes, it wont return. And it's my mistake.
I made this stupid assumption of skipping few fields which I thought that they won't be really required.

So yeah, API wrappers shouldn't really make any assumptions, return the data as is.
I will fix this by today, please do a `npm update` later to get the changes.

**Comment by UtsavPreet** [comment]
I can understand that.
Thank You so much :)

**Comment by jayeshsolanki93** [comment]
@UtsavPreet Bump the version to 1.1.0. I have changed it.
